### PR TITLE
fix: expanded offer closing automatically

### PR DESCRIPTION
**Pull request by samb-local**
Task: LOCAL-872

### CODE REVIEW

**Comment by davirds** [comment]
@samb-local it looks like the ExpandedOffer input fields are having some unexpected behavior:
- When I type a value into the fiat input field, it changes back to 0. 
- When I type any value into the crypto input field, it does not change the fiat input field to show me the conversion.

**Review by davirds — CHANGES_REQUESTED** [review]
Please take a look at the unexpected behavior of the ExpandedOffer input fields.

**Comment by davirds** [comment]
why did you close this task? Are you going to create another PR?

**Comment by samb-local** [comment]
Yes. A new one from the new branch will be sent.

**Pull request closed without merging**
